# Ansible Inventory - Generated by Terraform
# Do not edit

[all]
%{ for name, data in vms ~}
${data.domain} ansible_host=${data.interfaces[0].addrs[0].addr} ansible_user=${nodes[name].user}
%{ endfor ~}

%{ for name, node in nodes ~}
[${node.role}]
${node.hostname}

%{ endfor ~}
[all:vars]
ansible_ssh_private_key_file = ${ssh}
