# Ansible Inventory - Generated by Terraform
# Masters: ${length(masters)} | Workers: ${length(workers)}

[all]
%{ for name, data in vms ~}
${data.domain} ansible_host=${data.interfaces[0].addrs[0].addr} ansible_user=ubuntu
%{ endfor ~}

[masters]
%{ for name, vm in masters ~}
${vm.hostname}
%{ endfor ~}

[workers]
%{ for name, vm in workers ~}
${vm.hostname}
%{ endfor ~}

[load_balancer]
%{ for name, vm in lb ~}
${vm.hostname}
%{ endfor ~}

[k8s:children]
masters
workers

[all:vars]
ansible_ssh_private_key_file = ${ssh}
ansible_python_interpreter = /usr/bin/python3
